spring:
  application:
    name: Pulselist

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri:
          issuer-uri:

  firebase:
    project-id: ${FIREBASE_PROJECT_ID}

server:
  port: 8081

discogs:
  api:
    base-url: https://api.discogs.com
    token: ${DISCOGS_TOKEN}
    user-agent: ${DISCOGS_USER_AGENT}